AppBundle\Entity\Cursos:
    type: entity
    table: cursos
    repositoryClass: AppBundle\Repository\CursoRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        descripcion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        precio:
            type: float
            nullable: false
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
